---

- name: Add azlux apt key
  apt_key:
    url: https://azlux.fr/repo.gpg.key
    id: 98B824A5FA7D3A10FDB225B7CA548A0A0312D8E6
    state: present

- name: Add azlux apt source
  apt_repository:
    repo: deb http://packages.azlux.fr/debian/ buster main
    filename: azlux
    state: present
  register: log2ram_apt_source

- name: Update apt cache
  apt:
    update_cache: true
  when: log2ram_apt_source.changed

- name: Install log2ram
  apt:
    name: log2ram
    state: present
  register: log2ram_apt

- name: Write logs only weekly
  ini_file:
    path: /etc/systemd/system/log2ram-daily.timer.d/override.conf
    section: Timer
    option: OnCalendar
    value: weekly
    mode: 0644

- name: Ensure log2ram is running on startup
  systemd:
    name: log2ram
    daemon_reload: true
    enabled: true

- name: Reboot the Raspberry for changes to apply
  reboot:
  when: log2ram_apt.changed
