---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname | replace('_', '-') }}"

- name: Remove initial setup wizard
  file:
    path: /etc/xdg/autostart/piwiz.desktop
    state: absent

- name: Set user password
  user:
    name: pi
    password: "{{ pi_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
