---

# k3s server variables
k3s_control_node: true
k3s_etcd_datastore: true
k3s_use_experimental: true
k3s_server:
  secrets-encryption: true
  disable:
    - servicelb
    - traefik
  tls-san:
    - "{{ kube_vip_address }}"
  node-taint:
    - "node-role.kubernetes.io/master=true:NoSchedule"

k3s_server_manifests_urls:
  - url: https://kube-vip.io/manifests/rbac.yaml
    filename: kube-vip-rbac.yaml
  - url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/namespace.yaml"
    filename: metallb-namespace.yaml
  - url: "https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/manifests/metallb.yaml"
  - url: "https://raw.githubusercontent.com/longhorn/longhorn/{{ longhorn_version }}/deploy/longhorn.yaml"
  - url: "https://github.com/cert-manager/cert-manager/releases/download/{{ certmanager_version }}/cert-manager.yaml"
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_referencepolicies.yaml
    filename: 04-apiextensions.k8s.io_v1_customresourcedefinition_referencepolicies.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
    filename: 01-apiextensions.k8s.io_v1_customresourcedefinition_gatewayclasses.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
    filename: 02-apiextensions.k8s.io_v1_customresourcedefinition_gateways.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
    filename: 03-apiextensions.k8s.io_v1_customresourcedefinition_httproutes.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
    filename: 05-apiextensions.k8s.io_v1_customresourcedefinition_tcproutes.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
    filename: 06-apiextensions.k8s.io_v1_customresourcedefinition_tlsroutes.gateway.networking.k8s.io.yaml
  - url: https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
    filename: 07-apiextensions.k8s.io_v1_customresourcedefinition_udproutes.gateway.networking.k8s.io.yaml

k3s_server_manifests_templates:
  - kube-vip.yaml.j2
  - metallb-config.yaml.j2
  - traefik-chart.yaml.j2
  - cert-manager-config.yaml.j2
  - letsencrypt-issuer.yaml.j2

kube_vip_version: v0.4.2
kube_vip_interface: "{{ ansible_facts.default_ipv4.interface }}"
kube_vip_address: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    61303837346534633164343566386135386237376538366139383534333638653236323938366437
    6266623665636239656533646134353462653031306566300a613630613034376637386638333830
    36336362616638363730323137656366376338336632646638636565303131383930653736393636
    3731626236326132650a383834373364663637363837633039396132316565643739393164643730
    3565

metallb_version: v0.11.0
metallb_address: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    31633837343335306463386262336233356433636330633861316435623365353030363130313837
    6639646535643035303438646637363233613861663136370a346662383839656661356535383331
    63646533323761356134633337376637333862613535343564633763353234303139373830653464
    6238346563353262350a346233616366316137613964353634386666366561323137336230663434
    3765

longhorn_version: v1.2.3

certmanager_version: v1.7.1

gateway_api_version: v0.4.1
