---

# k3s server variables
k3s_control_node: true
k3s_etcd_datastore: true
k3s_use_experimental: true
k3s_server:
  secrets-encryption: true
  node-taint:
    - "node-role.kubernetes.io/master=true:NoSchedule"
