---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: drone
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: drone-server
      namespace: drone
    - kind: HelmRelease
      name: drone-runner
      namespace: drone
  providerRef:
    name: alertmanager
