---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: drone-server
  namespace: flux-system
spec:
  image: ghcr.io/andrasmaroy/drone-charts/drone
  interval: 24h0m0s

---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: drone-runner
  namespace: flux-system
spec:
  image: ghcr.io/andrasmaroy/drone-charts/drone-runner-kube
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: drone-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: drone-server
  policy:
    semver:
      range: '*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: drone-runner
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: drone-runner
  policy:
    semver:
      range: '*'
