---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets-server.sops.yaml
  - secrets-runner.sops.yaml
  - repository.yaml
  - release-server.yaml
