---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release-server.yaml
  - release-runner.yaml
  - image-updates.yaml
  - alerts.yaml

configMapGenerator:
  - name: policy
    namespace: drone
    files:
      - policy.yaml
secretGenerator:
  - name: server
    namespace: drone
    envs:
      - secrets-server.sops.env
  - name: runner
    namespace: drone
    envs:
      - secrets-runner.sops.env
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
