---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-server
  namespace: drone
spec:
  chart:
    spec:
      chart: drone
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: drone
      version: 0.6.3  # {"$imagepolicy": "flux-system:drone-server:tag"}
  values:
    updateStrategy:
      type: Recreate
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: webpublic
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: ci.${DOMAIN_PUBLIC}
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    persistentVolume:
      storageClass: longhorn
      annotations:
        helm.sh/resource-policy: keep
    extraSecretNamesForEnvFrom:
      - drone-server
    env:
      DRONE_LOGS_COLOR: true
      DRONE_LOGS_PRETTY: true
      DRONE_LOGS_TEXT: true
      DRONE_REGISTRATION_CLOSED: true
      DRONE_SERVER_HOST: ci.${DOMAIN_PUBLIC}
      DRONE_SERVER_PORT: ":80"
      DRONE_SERVER_PRIVATE_MODE: true
      DRONE_SERVER_PROTO: https
      DRONE_STATUS_DISABLED: true
  interval: 1m0s
