---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner
  namespace: drone
spec:
  chart:
    spec:
      chart: drone-runner-kube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: drone
      version: 0.1.10  # {"$imagepolicy": "flux-system:drone-runner:tag"}
  interval: 1m0s
  values:
    fullnameOverride: drone-runner
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    extraSecretNamesForEnvFrom:
      - drone-runner
    rbac:
      buildNamespaces:
        - drone
    env:
      DRONE_NAMESPACE_DEFAULT: drone
      DRONE_RPC_HOST: drone-server:8080
