---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone-runner
  namespace: drone
spec:
  chart:
    spec:
      chart: drone-runner-kube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: drone
      version: 0.1.10  # {"$imagepolicy": "flux-system:drone-runner:tag"}
  interval: 1m0s
  values:
    fullnameOverride: drone-runner
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE
      readOnlyRootFilesystem: true
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
    extraSecretNamesForEnvFrom:
      - runner
    rbac:
      buildNamespaces:
        - drone
    env:
      DRONE_NAMESPACE_DEFAULT: drone
      DRONE_POLICY_FILE: /policy.yml
      DRONE_RPC_HOST: drone-server:8080
    extraVolumes:
      - name: policy
        configMap:
          name: policy
    extraVolumeMounts:
      - name: policy
        mountPath: /policy.yaml
        subPath: policy.yaml
