apiVersion: v1
stringData:
    DRONE_RPC_SECRET: ENC[AES256_GCM,data:0JAfPmDC3aDPmcheTH9QJKGnyBAGMUKqb4DzdrRHr3o=,iv:8VmoTDEZOMtSeLEB2LWJMc8C6VaBka3hSzTl6eKarg8=,tag:4xJqwnLWGekpkWTLuZygmg==,type:str]
kind: Secret
metadata:
    name: drone-runner
    namespace: drone
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-19T22:07:16Z"
    mac: ENC[AES256_GCM,data:H8pBm5mn/UxSE5KaYg+eqgiL3CJPfaaZxyPCXNpwTyb/jVBd0gCZrBOIryphfdYfrr0p+W9yLimF8iJUvH1zV95UC/7xbF4jvuTwJN3XyDES8C99BedXLIr7EzCN5Ek/BiK6w9QbzfM8PjxiDyoheE3qpmbJvfdchH2V8zTcR9Y=,iv:nfFYPzqpaL1Wm2RlnKU7wQpDjBU+Aird4WTA1goLkIs=,tag:8eSi7M1glrQa769Jmje2yw==,type:str]
    pgp:
        - created_at: "2023-01-19T21:14:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/2zKbmHCsRnAQ/9GEw3utDVAZyBKPX/RXBZIEMkPyGtlJPcBQJEK92NP9rg
            ZTAalINb6cC+ZMqkgUBX0xnrlQlVL+8hPIFWuy9ZPx28ope/bqx1OFGg7/CcnI5e
            GdEBlV01o8iObCRC2J9dHMd5alz5n+3B2u4+cBSS0KcrYm9vWrBXIjh5k8o3Viu9
            1b4ZaO7rZGW8nC39TknxV/QZcg11FkXNFeQKhQpCg60IVmOwvnvhO8Bsk/lW1sjU
            ZmBZS02OJDd7mYtsEd6ygp3yo3mbwz5QCvIkoZ7dcaw5tA9wDi2H84709U0qIa4D
            fRcXJKJW00Vu3azcLIvN9R3cDO/SyMmvim981E/sKnUpoZn5+hwOFuKKM8PjxHXL
            4CfLtiUtbBUgqyuZLoi2a8GacLMGIw9qrb8D1Hz7YmEHppqbOhBtEdzeNUd5ofVD
            lVylKtv5X+9wVEcR9YVXfLTRkW3bq35wKcRupXlTZRVz0WkwrKl2adtcs+Qwxpx0
            YEh0Wt3BMxF3i6+6DNCPiMhHki80NpAqXd/Hb2FEmHhh8WaO43pr/VxQkO0m7+UR
            IfcR2qgvkbC4mUasNmLxdzReabBR276pqCmwtsZLEU9T8o/V47ywbsmV9UnwE23G
            h3wWKIv+BCbHawNgb/d0TYlPrjmC3NDrv2f8q9ZkseODGzTteZmWbyhROKe/Fm7S
            XAGLCIFlIIeg8+CTQjZJ1qmQ+d4E038mVH2M6cPS/isazR3+pU3QPjlK9tpCpnsV
            furJ9ObBRY9YXXQpyQAJj8/DNPwKXGCZ6rOqXyG5IhPVHsFxlaqMKZxA9RDB
            =2Qk6
            -----END PGP MESSAGE-----
          fp: 976AA83A5066FFE4CF485376F76C07C5F5BB0BEB
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
