---

- name: Add backports apt source
  ansible.builtin.apt_repository:
    repo: deb http://deb.debian.org/debian/ {{ ansible_distribution_release }}-backports main contrib non-free
    filename: "{{ ansible_distribution_release }}-backports"

- name: Install appropriate kernel headers
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
  register: kernel_headers

- name: Install ZFS
  ansible.builtin.apt:
    name: zfsutils-linux
    default_release: "{{ ansible_distribution_release }}-backports"

- name: Rebuild zfs kernel module if needed
  shell: apt install --reinstall zfs-dkms
  when: kernel_headers.changed

- name: Load ZFS modules
  community.general.modprobe:
    name: zfs
    state: present
