---

# Since the root filesystem is encrypted, it is safe to store keys for the
# ZFS volumes on it for auto unlocking. ZFS doesn't support TPM for this
# purpose, so this is the next best thing.
- name: Create keystore folder
  ansible.builtin.file:
    group: root
    mode: 0700
    owner: root
    path: /etc/keystore
    state: directory

- name: Include zfs vols file
  ansible.builtin.include_vars:
    file: zfs_vols.yml
  no_log: true

# Store the actual encryption keys with strict permissions. Keys are 32 byte
# long hex strings.
- name: Persist ZFS encryption keys
  ansible.builtin.copy:
    content: "{{ zfs_vols[item].key }}"
    dest: "/etc/keystore/tank-{{ item | lower() }}.key"
    group: root
    mode: 0400
    owner: root
  no_log: true
  when: zfs_vols[item].key is defined
  loop: "{{ zfs_vols.keys() }}"

# Create the volumes, encryption and other properties defined in the extra
# properties field.
- name: Create volumes
  community.general.zfs:
    name: "tank/{{ item }}"
    state: present
    extra_zfs_properties: "{{ zfs_vols[item].extra_zfs_properties | default({}) }}"
  loop: "{{ zfs_vols.keys() }}"
