---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  image: ghcr.io/prometheus-community/charts/kube-prometheus-stack
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kube-prometheus-stack
  policy:
    semver:
      range: '*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: prometheus-smartctl-exporter
  namespace: flux-system
spec:
  image: ghcr.io/prometheus-community/charts/prometheus-smartctl-exporter
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prometheus-smartctl-exporter
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prometheus-smartctl-exporter
  policy:
    semver:
      range: '*'
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: prometheus-blackbox-exporter
  namespace: flux-system
spec:
  image: ghcr.io/prometheus-community/charts/prometheus-blackbox-exporter
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: prometheus-blackbox-exporter
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prometheus-blackbox-exporter
  policy:
    semver:
      range: '*'
