---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release-prometheus-stack.yaml
  - release-smartctl-exporter.yaml
  - release-blackbox-exporter.yaml
  - release-postgres-exporter.yaml
  - zfs-exporter.yaml
  - cert-manager.yaml
  - traefik.yaml
  - vernemq.yaml
  - image-updates.yaml
  - alerts.yaml

secretGenerator:
  - name: alertmanager-secrets
    namespace: monitoring
    envs:
      - alertmanager-secrets.sops.env
  - name: cluster-info
    namespace: monitoring
    envs:
      - cluster-info.sops.env
  - name: grafana-admin
    namespace: monitoring
    envs:
      - grafana-admin.sops.env
  - name: postgres-secrets
    namespace: monitoring
    envs:
      - postgres-secrets.sops.env

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
