apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-smartctl-exporter
  namespace: monitoring
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: 0.15.4 # {"$imagepolicy": "flux-system:prometheus-smartctl-exporter:tag"}
  values:
    nodeSelector:
      kubernetes.io/arch: amd64
      node.longhorn.io/create-default-disk: "true"
    prometheusRules:
      enabled: true
      extraLabels:
        release: prom
    resources:
      limits:
        memory: 26Mi
      requests:
        cpu: 10m
        memory: 16Mi
    serviceMonitor:
      enabled: true
      extraLabels:
        release: prom
