---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: monitoring
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
      version: 8.4.0
  values:
    pspEnabled: false
    resources:
      limits:
        memory: 42Mi
      requests:
        cpu: 5m
        memory: 20Mi
    serviceMonitor:
      selfMonitor:
        enabled: true
        labels:
          release: prom
    extraManifests:
      - apiVersion: monitoring.coreos.com/v1
        kind: Probe
        metadata:
          name: ingress
          namespace: monitoring
          labels:
            app.kubernetes.io/instance: prometheus-blackbox-exporter
            app.kubernetes.io/name: prometheus-blackbox-exporter
            release: prom
        spec:
          interval: 30s
          module: http_2xx
          prober:
            url: prometheus-blackbox-exporter.monitoring.svc:9115
          scrapeTimeout: 30s
          targets:
            ingress:
              namespaceSelector:
                any: true
              relabelingConfigs:
                - action: keep
                  regex: /
                  sourceLabels:
                    - __meta_kubernetes_ingress_path
              selector:
                matchLabels:
                  probe: enabled
