---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: monitoring
spec:
  interval: 5m0s
  type: "oci"
  url: oci://ghcr.io/prometheus-community/charts
