---

- name: Add YugabyteDB helm repository
  kubernetes.core.helm_repository:
    name: yugabyte
    url: https://charts.yugabyte.com

- name: Install YugabyteDB
  kubernetes.core.helm:
    name: yugabyte
    chart_ref: yugabyte/yugabyte
    namespace: yugabyte
    chart_version: "{{ yugabyte_chart_version }}"
    update_repo_cache: true
    create_namespace: true
    atomic: true
    values:
      resource:
        master:
          requests:
            cpu: 0.5
            memory: 0.5Gi
        tserver:
          requests:
            cpu: 0.5
            memory: 0.5Gi
      storage:
        master:
          storageClass: longhorn
        tserver:
          storageClass: longhorn
      # Yugabyte doesn't publish docker images for arm at the moment
      # Open issue: https://github.com/yugabyte/yugabyte-db/issues/11499
      nodeSelector:
        kubernetes.io/arch: amd64
      enableLoadBalancer: false

- name: Add route for YugabyteDB UI
  kubernetes.core.k8s:
    definition:
      apiVersion: gateway.networking.k8s.io/v1alpha2
      kind: HTTPRoute
      metadata:
        name: yugabyte
        namespace: yugabyte
      spec:
        parentRefs:
          - name: traefik
            namespace: kube-system
            group: gateway.networking.k8s.io
            kind: Gateway
        hostnames:
          - yugabyte.kubi.{{ domain_local }}
        rules:
          - backendRefs:
              - name: yb-masters
                namespace: yugabyte
                port: 7000
                weight: 1
                group: ""
                kind: Service
            matches:
              - path:
                  type: PathPrefix
                  value: /
