apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.4.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/koenkk/zigbee2mqtt
      tag: "1.30.3" # {"$imagepolicy": "flux-system:zigbee2mqtt:tag"}
      pullPolicy: IfNotPresent
    env:
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: z2m.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        enabled: true
        storageClass: longhorn
        retain: true
        accessMode: ReadWriteOnce
        size: 100Mi
        mountPath: /data
      secrets:
        enabled: true
        type: secret
        name: zigbee2mqtt
        subPath:
          - path: secrets.yaml
            mountPath: /data/secrets.yaml
          - path: devices
            mountPath: /data/devices.yaml
      config:
        enabled: true
        type: configMap
        name: zigbee2mqtt
        mountPath: /data/configuration.yaml
        subPath: configuration.yaml
    resources:
      limits:
        memory: 160Mi
      requests:
        cpu: 10m
        memory: 80Mi
