apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        containers:
          main:
            env:
              TZ: ${TZ}
              ZIGBEE2MQTT_DATA: /data
            image:
              repository: docker.io/koenkk/zigbee2mqtt
              tag: "2.1.1" # {"$imagepolicy": "flux-system:zigbee2mqtt:tag"}
              pullPolicy: IfNotPresent
            nameOverride: zigbee2mqtt
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            resources:
              limits:
                memory: 160Mi
              requests:
                cpu: 10m
                memory: 80Mi
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:zigbee
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: z2m.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      data:
        accessMode: ReadWriteOnce
        enabled: true
        retain: true
        size: 100Mi
        storageClass: longhorn
      secrets:
        enabled: true
        globalMounts:
          - path: /data/secrets.yaml
            subPath: secrets.yaml
          - path: /data/devices.yaml
            subPath: devices
        name: zigbee2mqtt
        type: secret
      config:
        enabled: true
        globalMounts:
          - path: /data/configuration.yaml
            subPath: configuration.yaml
        name: zigbee2mqtt
        type: configMap
    service:
      main:
        ports:
          http:
            port: 8080
