apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: pihole
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      version: 2.18.0
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    image:
      tag: "2023.05.2" # {"$imagepolicy": "flux-system:pihole:tag"}
    strategyType: Recreate
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: ${METALLB_ADDRESS}
      annotations:
        metallb.universe.tf/allow-shared-ip: "metallb-shared-ip"
      externalTrafficPolicy: Cluster
    serviceDhcp:
      enabled: false
    serviceWeb:
      https:
        enabled: false
    virtualHost: pihole.kubi.${DOMAIN_LOCAL}
    probes:
      liveness:
        type: command
        command:
          - /bin/sh
          - '-c'
          - dig +short +norecurse +retry=0 @127.0.0.1 pi.hole
          - '||'
          - exit 1
    ingress:
      enabled: true
      annotations:
        hajimari.io/icon: mdi:pi-hole
        hajimari.io/appName: pi-hole
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - pihole.kubi.${DOMAIN_LOCAL}
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    persistentVolumeClaim:
      enabled: true
      size: 1Gi
      storageClass: longhorn
      annotations:
        helm.sh/resource-policy: keep
    admin:
      existingSecret: admin
      passwordKey: password
    extraEnvVars:
      TZ: ${TZ}
      DNS_BOGUS_PRIV: "true"
      DNS_FQDN_REQUIRED: "true"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: ${DOMAIN_LOCAL}
      REV_SERVER_TARGET: ${ROUTER_IP}
      REV_SERVER_CIDR: ${NETWORK}
    DNS1: "1.1.1.1;1.0.0.1;9.9.9.9"
    DNS2: ${ROUTER_IP}
    adlists:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
      - https://blocklistproject.github.io/Lists/abuse.txt
      - https://blocklistproject.github.io/Lists/ads.txt
      - https://blocklistproject.github.io/Lists/fraud.txt
      - https://blocklistproject.github.io/Lists/malware.txt
      - https://blocklistproject.github.io/Lists/phishing.txt
      - https://blocklistproject.github.io/Lists/ransomware.txt
      - https://blocklistproject.github.io/Lists/redirect.txt
      - https://blocklistproject.github.io/Lists/scam.txt
      - https://blocklistproject.github.io/Lists/tracking.txt
    whitelist:
      - bugmenot.com
    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - ${ROUTER_IP}
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: networking.k8s.io
              kind: Ingress
              name: pihole
              version: v1
            patch:
              - op: add
                path: /metadata/labels/probe
                value: enabled
