---
DNS1: 1.1.1.1;1.0.0.1;9.9.9.9
DNS2: 10.79.18.1
adlists:
- https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
- https://blocklistproject.github.io/Lists/abuse.txt
- https://blocklistproject.github.io/Lists/ads.txt
- https://blocklistproject.github.io/Lists/fraud.txt
- https://blocklistproject.github.io/Lists/malware.txt
- https://blocklistproject.github.io/Lists/phishing.txt
- https://blocklistproject.github.io/Lists/ransomware.txt
- https://blocklistproject.github.io/Lists/redirect.txt
- https://blocklistproject.github.io/Lists/scam.txt
- https://blocklistproject.github.io/Lists/tracking.txt
admin:
  existingSecret: admin-dc69kmd2hb
  passwordKey: password
env:
  TZ: Europe/Budapest
extraEnvVars:
  DNS_BOGUS_PRIV: "true"
  DNS_FQDN_REQUIRED: "true"
  REV_SERVER: "true"
  REV_SERVER_CIDR: 10.79.0.0/16
  REV_SERVER_DOMAIN: baross.local.andrasmaroy.eu
  REV_SERVER_TARGET: 10.79.18.1
  TZ: Europe/Budapest
image:
  tag: 2023.05.2
ingress:
  annotations:
    hajimari.io/appName: pi-hole
    hajimari.io/icon: mdi:pi-hole
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  enabled: true
  hosts:
  - pihole.kubi.baross.local.andrasmaroy.eu
  labels:
    probe: enabled
persistentVolumeClaim:
  annotations:
    helm.sh/resource-policy: keep
  enabled: true
  size: 1Gi
  storageClass: longhorn
podDnsConfig:
  enabled: true
  nameservers:
  - 127.0.0.1
  - 10.79.18.1
  policy: None
probes:
  liveness:
    command:
    - /bin/sh
    - -c
    - dig +short +norecurse +retry=0 @127.0.0.1 pi.hole
    - '||'
    - exit 1
    type: command
resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceDhcp:
  enabled: false
serviceDns:
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-shared-ip
  externalTrafficPolicy: Cluster
  loadBalancerIP: 10.79.28.20
  type: LoadBalancer
serviceWeb:
  https:
    enabled: false
strategyType: Recreate
virtualHost: pihole.kubi.baross.local.andrasmaroy.eu
whitelist:
- bugmenot.com
