---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - image-updates.yaml
  - alerts.yaml


configMapGenerator:
  - name: esphome-devices
    namespace: home-automation
    files:
      - devices/living-room-ac.yaml
secretGenerator:
  - name: esphome
    namespace: home-automation
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
    files:
      - secrets.yaml=secrets.sops.yaml
configurations:
  - kustomizeconfig.yaml
