apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.5.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          nodeSelector:
            kubernetes.io/hostname: nas
        containers:
          main:
            env:
              ESPHOME_DASHBOARD_USE_PING: false
              ESPHOME_DASHBOARD_RELATIVE_URL: "/"
              HOME: "/config"
              TZ: ${TZ}
            image:
              repository: docker.io/esphome/esphome
              tag: "2023.12.8" # {"$imagepolicy": "flux-system:esphome:tag"}
              pullPolicy: IfNotPresent
            nameOverride: esphome
            ports:
              - containerPort: 6052
                name: http
                protocol: TCP
            securityContext:
              readOnlyRootFilesystem: true
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 100m
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:car-esp
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: esphome.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        type: emptyDir
      devices:
        enabled: true
        globalMounts:
          - path: /config/living-room-ac.yaml
            subPath: living-room-ac.yaml
        name: esphome-devices
        type: configMap
      secrets:
        enabled: true
        globalMounts:
          - path: /config/secrets.yaml
            subPath: secrets.yaml
        name: esphome
        type: secret
    service:
      main:
        ports:
          http:
            port: 6052
