apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.5.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/esphome/esphome
      tag: "2023.4.4" # {"$imagepolicy": "flux-system:esphome:tag"}
      pullPolicy: IfNotPresent
    env:
      ESPHOME_DASHBOARD_USE_PING: false
      ESPHOME_DASHBOARD_RELATIVE_URL: "/"
      HOME: "/config"
      readOnlyRootFilesystem: true
    service:
      main:
        ports:
          http:
            port: 6052
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: esphome.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    nodeSelector:
      kubernetes.io/hostname: nas
    persistence:
      config:
        enabled: true
        type: emptyDir
      devices:
        enabled: true
        name: esphome-devices
        type: configMap
        subPath:
          - path: living-room-ac.yaml
            mountPath: /config/living-room-ac.yaml
      secrets:
        enabled: true
        type: secret
        name: esphome
        mountPath: /config/secrets.yaml
        subPath: secrets.yaml
    resources:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
