wifi_ssid: ENC[AES256_GCM,data:dIEM4JvcYNQzeIYz,iv:jbUcx2MoGr0YP7LG2XC8FGLi8pjWkMexX6/Z2w5WvH8=,tag:hRHc0vQ0F0O3HWjangAXDw==,type:str]
wifi_password: ENC[AES256_GCM,data:Kcj+prUCYKDcVGy/LuxlfkhR7irOX1eiyBZBn96WBaHLuuAj6F8UippMJV6zx+JGDrtUGKpuCaLEflvZB2Ez,iv:RmjNfRnQromrdhwdScwYFaSJFc2FHNT2nN20TgT9rg4=,tag:jYvaptfcxooeHapauGY4Jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-24T16:13:54Z"
    mac: ENC[AES256_GCM,data:1/spNE7uq/nXanqYgb1CEcqgFoCmtm6OaYVjW5VR9YK23cL0aryVsUgk4uJnot7vPJA8rWhxbl2vYzvxpQTEatjPow0bxcx2dBZveniwvS3bp4bR3MQY4N0+I59KT8ZgBGfRoZVvThuIvR1onsD8KTg4U7NdtlPFYpFCiWgPQ/c=,iv:mTYcH/V9vZJ6jQ5f/8j/1HwMbvwsHa8cyHOu+yu5I1c=,tag:43UjrG/82Tuo+aZZFGLm6w==,type:str]
    pgp:
        - created_at: "2023-02-05T09:02:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/2zKbmHCsRnAQ//X3y9Yied5dggMmJzDUk8wFX/6X9sCy2sjhgg9lvcrlWy
            Ep4wC/c/5mfj/YnNwPkNTHvNinGo4akps+vZMrw7eOXhcJdFULzHJV+oxog0Dc1M
            ZZHocL9ytBRYzJNtCUxGSdybe4TRdIM2+KCnOjGxrmF3O8iEAaFOePtZnhIHAPuA
            7HbjcYgnCBBONCBafX1mGWnLs8S/wk8ZJo4y9ojhGfDvae/kjBJtM9nWB2ohYIyW
            eBXokHHok5pfuVwshInaaD1VF/uyPoDJWfoYuDelMO03TDB9tirXay10Wyr61Dct
            GJcz+HAFLnT2lluFyPbM6gnpNzUlettHbjLJEZZ/5DnyBp3CWSHC0cD6KrF+wnMY
            gYU1RXOOm9Iy9TT1GEFQD6x33tuW846X6r/ClMfOUJpIM2PrFMGLA0i9wXHydb6G
            6PWK29FLEGQuMoOMxTlZoUKE8gBD3ScaJ759/8zsdt6zQtRFXKGlRqp2hxyxGVOL
            M3Cz00mHKkrh+RL6Ek6i4L2CpzqKEye/fw7Y6LS7vi9XP8d8o6jG0grQi+1pxTm5
            qrAkv2JdgzcAiTRdHv/wTDCJaeEzAHzYCMh61lT1s1ALQBjR/GBAPd7DLkZBtqyj
            KCfudRaqZhJzDZ48/z2MPxWhJcJEaodrrBvRSD5oe9Ure2CQTG6DPpxmYnf9/x7S
            XgFlgQs6DIJsBYKUEJ/7L+nrJ8i+usIcOQTheOvZIcf31iobRIC8m0nIdLOBbw6J
            Qbg81NpdqttGsCtwe/jbEgUgiHdYixlmCympTv3wSLfi74gxdtlqGBBPCGH54MI=
            =pVDn
            -----END PGP MESSAGE-----
          fp: 976AA83A5066FFE4CF485376F76C07C5F5BB0BEB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
