---
kind: pipeline
type: kubernetes
name: Terraform Daily Plan

steps:
  - name: Terraform Plan
    image: hashicorp/terraform:1.3.7
    environment:
      SOPS_GPG_KEY:
        from_secret: sops
      TF_TOKEN_app_terraform_io:
        from_secret: terraform_cloud_token
    commands:
      - mkdir -p /root/.gnupg
      - chmod 0700 /root/.gnupg
      - echo "$SOPS_GPG_KEY" > /root/.gnupg/sops.asc
      - apk update
      - apk add gpg gpg-agent
      - gpg --import /root/.gnupg/sops.asc
      - wget https://github.com/mozilla/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64 -O /usr/local/bin/sops
      - chmod +x /usr/local/bin/sops
      - cd terraform/flux
      - terraform init -lockfile=readonly
      - terraform validate
      - terraform plan -detailed-exitcode

node_selector:
  kubernetes.io/arch: amd64
