---
kind: pipeline
type: kubernetes
name: terraform

steps:
  - name: terraform
    image: jmccann/drone-terraform:5
    actions:
      - validate
      - plan

node_selector:
  kubernetes.io/arch: amd64
