---
kind: pipeline
type: kubernetes
name: terraform

steps:
  - name: terraform
    image: hashicorp/terraform:1.3.7
    actions:
      - validate
      - plan

node_selector:
  kubernetes.io/arch: amd64
