---
kind: pipeline
type: kubernetes
name: Terraform Daily Plan

steps:
  - name: Terraform Plan
    image: hashicorp/terraform:1.3.7
    environment:
      TF_TOKEN_app_terraform_io:
        from_secret: terraform_cloud_token
    commands:
      - cd terraform/flux
      - terraform init -lockfile=readonly
      - terraform validate
      - terraform plan -detailed-exitcode

node_selector:
  kubernetes.io/arch: amd64
