---

roles:
  - name: geerlingguy.nodejs
  - name: maxhoesel.nut_netclient
  - name: ntd.nut
  - src: https://github.com/andrasmaroy/ansible-role-zigbee2mqtt
    name: andrasmaroy.zigbee2mqtt

collections:
  - name: ansible.netcommon
  - name: git@github.com:andrasmaroy/iot_ac.git#/ansible
    type: git
