---

roles:
  - name: geerlingguy.nodejs
    version: 6.0.0
  - name: maxhoesel.nut_netclient
    version: 2fe3b38
  - name: ntd.nut
    version: 1.3.0
  - name: zfuller.pihole
    src: https://github.com/andrasmaroy/pihole.git
  - name: xanmanning.k3s
    version: v3.1.0
  - name: andrasmaroy.zigbee2mqtt
    src: https://github.com/andrasmaroy/ansible-role-zigbee2mqtt

collections:
  - name: ansible.netcommon
    version: 2.5.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.3.0
  - name: community.network
    version: 3.0.0
  - name: community.routeros
    version: 2.0.0
  - name: git@github.com:andrasmaroy/iot_ac.git#/ansible
    type: git
  - name: git@github.com:andrasmaroy/iot_baby.git#/ansible
    type: git
