---

roles:
  - name: geerlingguy.nodejs
  - name: maxhoesel.nut_netclient
  - name: ntd.nut
  - name: zfuller.pihole
    src: https://github.com/andrasmaroy/pihole.git
  - name: andrasmaroy.zigbee2mqtt
    src: https://github.com/andrasmaroy/ansible-role-zigbee2mqtt

collections:
  - name: ansible.netcommon
  - name: community.general
  - name: community.network
  - name: community.routeros
  - name: git@github.com:andrasmaroy/iot_ac.git#/ansible
    type: git
  - name: git@github.com:andrasmaroy/iot_baby.git#/ansible
    type: git
