---

roles:
  - name: geerlingguy.nfs
    version: 2.0.0
  - name: maxhoesel.nut_netclient
    version: 2fe3b38
  - name: ntd.nut
    version: 1.3.0
  - name: xanmanning.k3s
    version: v3.1.1

collections:
  - name: ansible.netcommon
    version: 2.5.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.crypto
    version: 2.0.2
  - name: community.general
    version: 4.3.0
  - name: community.network
    version: 3.0.0
  - name: community.routeros
    version: 2.0.0
  - name: kubernetes.core
    version: 2.3.2
  - name: https://github.com/andrasmaroy/iot_baby.git#/ansible
    type: git
