---

- hosts: all
  roles:
    - base

- hosts: raspberry_pi
  roles:
    - raspberry_pi

- hosts: iot_ac
  collections:
    - andrasmaroy.iot_ac
  tasks:
    - import_role:
        name: iot_ac

- hosts: iot*
  roles:
    - iot
  vars_files:
    - group_vars/iot.yml
