---

- hosts: mikrotik
  roles:
    - mikrotik
  strategy: linear

- hosts: all:!mikrotik
  roles:
    - base

- hosts: nas
  roles:
    - luks_tpm
    - zfs
    - netatalk
    - users
    - geerlingguy.nfs
  vars_files:
    - vars/zpool_disks.yml

- hosts: u59
  roles:
    - intel_gpu

- hosts: k3s_server
  roles:
    - k3s_server

- hosts: k3s
  roles:
    - k3s
    - xanmanning.k3s
  tasks:
    - import_tasks: roles/k3s_server/tasks/kubeconfig.yml
      when: k3s_primary_control_node is defined and k3s_primary_control_node

- hosts: raspberry_pi
  roles:
    - raspberry_pi


- hosts: myst
  roles:
    - myst

- hosts: pihole
  roles:
    - ntd.nut
    - mdns_reflector

- hosts: iot_baby
  roles:
    - andrasmaroy.iot_baby.iot_baby

- hosts: nut_client
  roles:
    - maxhoesel.nut_netclient

- hosts: iot*
  roles:
    - iot
  vars_files:
    - group_vars/iot.yml
