---

- hosts: mikrotik
  roles:
    - mikrotik
  strategy: linear

- hosts: all:!mikrotik
  roles:
    - base

- hosts: nas
  roles:
    - ntd.nut

- hosts: k3s_agent
  roles:
    - k3s_agent

- hosts: k3s_server
  roles:
    - k3s_server

- hosts: k3s
  roles:
    - role: xanmanning.k3s
      # Remove check for iptables-legacy, as of v1.22.3 of K3S it is no longer
      # a hard dependency and works with nftables instead.
      # See: https://github.com/k3s-io/k3s/issues/4188
      k3s_check_packages:
        debian-11: []
  tasks:
    - import_tasks: roles/k3s_server/tasks/kubeconfig.yml
      when: k3s_primary_control_node is defined and k3s_primary_control_node

- name: Apply helm charts from localhost
  hosts: localhost
  connection: local
  vars:
    ansible_become: false
  roles:
    - k3s_gateway_api
    - helm_metallb
    - helm_longhorn
    - helm_cert_manager
    - helm_traefik
    - helm_kubernetes_dashboard
    - helm_yugabytedb
  environment:
    K8S_AUTH_KUBECONFIG: ~/.kube/kubi.yaml

- hosts: raspberry_pi
  roles:
    - raspberry_pi

- hosts: iot_ac
  roles:
    - geerlingguy.nodejs
    - andrasmaroy.zigbee2mqtt
    - andrasmaroy.iot_ac.iot_ac
  vars_files:
    - vars/zigbee_devices.yml

- hosts: myst
  roles:
    - myst

- hosts: pihole
  roles:
    - zfuller.pihole
  vars_files:
    - vars/pihole.yml

- hosts: iot_baby
  roles:
    - andrasmaroy.iot_baby.iot_baby

- hosts: nut_client
  roles:
    - maxhoesel.nut_netclient

- hosts: iot*
  roles:
    - iot
  vars_files:
    - group_vars/iot.yml
