---

- hosts: all
  roles:
    - base

- hosts: nas
  roles:
    - ntd.nut

- hosts: raspberry_pi
  roles:
    - raspberry_pi

- hosts: iot_ac
  roles:
    - geerlingguy.nodejs
    - andrasmaroy.iot_ac.iot_ac

- hosts: nut_client
  roles:
    - maxhoesel.nut_netclient

- hosts: iot*
  roles:
    - iot
  vars_files:
    - group_vars/iot.yml
