---

- hosts: mikrotik
  roles:
    - mikrotik
  strategy: linear

- hosts: all:!mikrotik
  roles:
    - base

- hosts: nas
  roles:
    - ntd.nut

- hosts: k3s_agent
  roles:
    - k3s_agent

- hosts: k3s
  roles:
    - xanmanning.k3s
    - k3s

- hosts: raspberry_pi
  roles:
    - raspberry_pi

- hosts: iot_ac
  roles:
    - geerlingguy.nodejs
    - andrasmaroy.zigbee2mqtt
    - andrasmaroy.iot_ac.iot_ac
  vars_files:
    - vars/zigbee_devices.yml

- hosts: myst
  roles:
    - myst

- hosts: pihole
  roles:
    - zfuller.pihole
  vars_files:
    - vars/pihole.yml

- hosts: iot_baby
  roles:
    - andrasmaroy.iot_baby.iot_baby

- hosts: nut_client
  roles:
    - maxhoesel.nut_netclient

- hosts: iot*
  roles:
    - iot
  vars_files:
    - group_vars/iot.yml
