---

- name: Add Longhorn helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    url: https://charts.longhorn.io

- name: Install Longhorn
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    namespace: longhorn-system
    chart_version: "{{ longhorn_version }}"
    update_repo_cache: true
    create_namespace: true
    atomic: true
    values:
      defaultSettings:
        createDefaultDiskLabeledNodes: true
      ingress:
        enabled: true
        host: longhorn.kubi.{{ domain_local }}
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"

- name: Add service-replicated-longhorn storage class
  kubernetes.core.k8s:
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: service-replicated-longhorn
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      parameters:
        numberOfReplicas: "1"
        dataLocality: "best-effort"
        staleReplicaTimeout: "2880"  # 48 hours in minutes
        fromBackup: ""
