---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patches:
  - path: tz_patch.yaml
    target:
      kind: HelmRelease
      group: helm.toolkit.fluxcd.io
      version: v2beta1
resources:
  - bjw-s-repository.yaml
  - drone
  - postgresql-ha
  - home-automation
  - media
  - pihole
