---

- name: Add MetalLB helm repository
  kubernetes.core.helm_repository:
    name: metallb
    url: https://metallb.github.io/metallb

- name: Install MetalLB
  kubernetes.core.helm:
    name: metallb
    chart_ref: metallb/metallb
    namespace: metallb-system
    chart_version: "{{ metallb_version }}"
    update_repo_cache: true
    create_namespace: true
    atomic: true
    values:
      configInline:
        address-pools:
          - name: default
            protocol: layer2
            addresses:
              - "{{ metallb_address }}/32"
