---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - alerts.yaml

secretGenerator:
  - name: valetudo-mapper
    namespace: home-automation
    files:
      - config.json=config.sops.json
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
