apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valetudo-mapper
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.1.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        containers:
          main:
            env:
              TZ: ${TZ}
            image:
              repository: docker.io/rand256/valetudo-mapper
              tag: latest
              pullPolicy: IfNotPresent
            nameOverride: valetudo-mapper
            ports:
              - containerPort: 3000
                name: http
                protocol: TCP
            resources:
              limits:
                memory: 96Mi
              requests:
                cpu: 1m
                memory: 64Mi
            securityContext:
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /app/config.json
            subPath: config.json
        name: valetudo-mapper
        type: secret
      tmp:
        enabled: true
        medium: Memory
        type: emptyDir
      root:
        enabled: true
        medium: Memory
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 3000
