apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valetudo-mapper
  namespace: home-automation
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.0.3 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/rand256/valetudo-mapper
      tag: latest
      pullPolicy: IfNotPresent
    env: {}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    service:
      main:
        ports:
          http:
            port: 3000
    persistence:
      config:
        enabled: true
        type: secret
        name: valetudo-mapper
        mountPath: /app/config.json
        subPath: config.json
      tmp:
        enabled: true
        type: emptyDir
        mountPath: /tmp
        medium: Memory
      tmp-root:
        enabled: true
        type: emptyDir
        mountPath: /root
        medium: Memory
    resources:
      limits:
        memory: 96Mi
      requests:
        cpu: 1m
        memory: 64Mi
