---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: vaultwarden
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: vaultwarden
      namespace: vaultwarden
  providerRef:
    name: alertmanager
