---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - tf-db.yaml
  - repository.yaml
  - release.yaml
  - alerts.yaml

secretGenerator:
  - name: vaultwarden
    namespace: vaultwarden
    envs:
      - secrets.sops.env
  - name: core-db-terraform
    namespace: vaultwarden
    options:
      disableNameSuffixHash: true
    envs:
      - ../../foundation/cnpg/tf-user.sops.env
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
