---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gissilabs
  namespace: vaultwarden
spec:
  interval: 5m0s
  url: https://nexus.kubi.${DOMAIN_LOCAL}/repository/gissilabs/
