---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: vaultwarden-db
  namespace: vaultwarden
spec:
  interval: 1m
  approvePlan: auto
  destroyResourcesOnDeletion: true
  path: ./kubernetes/home/apps/vaultwarden/terraform
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  varsFrom:
    - kind: Secret
      name: core-db-terraform
  writeOutputsToSecret:
    name: vaultwarden-db
