---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cnpg
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: cnpg
      namespace: cnpg-system
  providerRef:
    name: alertmanager
