---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - alerts.yaml
  - cluster.yaml

secretGenerator:
  - name: core-terraform
    namespace: cnpg-system
    envs:
      - tf-user.sops.env
    type: kubernetes.io/basic-auth

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    cnpg.io/reload: "true"
