---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-system
spec:
  interval: 5m0s
  url: https://nexus.kubi.${DOMAIN_LOCAL}/repository/cnpg/
