---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rtorrent-flood
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.3.1
  values:
    image:
      repository: docker.io/jesec/rtorrent-flood
      tag: master-distroless
      pullPolicy: IfNotPresent

    env:
      FLOOD_OPTION_ALLOWEDPATH: "/downloads"
      FLOOD_OPTION_HOST: "0.0.0.0"
      FLOOD_OPTION_PORT: "3000"
      FLOOD_OPTION_RTORRENT: "true"
      HOME: "/config"

    configMaps:
      config:
        enabled: true
        data:
          .rtorrent.rc: |
            session.use_lock.set = no
            method.insert = cfg.basedir,  private|const|string, (cat,(fs.homedir),"/.local/share/rtorrent/")
            method.insert = cfg.download, private|const|string, (cat,"/downloads/","complete/")
            method.insert = cfg.logs,     private|const|string, (cat,(cfg.basedir),"log/")
            method.insert = cfg.logfile,  private|const|string, (cat,(cfg.logs),"rtorrent-",(system.time),".log")
            method.insert = cfg.session,  private|const|string, (cat,(cfg.basedir),".session/")
            fs.mkdir.recursive = (cat,(cfg.basedir))
            fs.mkdir = (cat,(cfg.download))
            fs.mkdir = (cat,(cfg.logs))
            fs.mkdir = (cat,(cfg.session))
            dht.mode.set = disable
            directory.default.set = (cat, (cfg.download))
            encoding.add = utf8
            log.execute = (cat, (cfg.logs), "execute.log")
            network.http.dns_cache_timeout.set = 25
            network.http.max_open.set = 50
            network.max_open_files.set = 600
            network.max_open_sockets.set = 300
            network.port_random.set = no
            network.port_range.set = 15329-15329
            network.scgi.open_local = (cat,(cfg.basedir),rtorrent.sock)
            pieces.memory.max.set = 1800M
            protocol.encryption.set = require,allow_incoming,try_outgoing
            protocol.pex.set = no
            session.path.set = (cat, (cfg.session))
            system.cwd.set = (directory.default)
            system.daemon.set = true
            system.umask.set = 0002
            throttle.max_peers.normal.set = 60
            throttle.max_peers.seed.set = 80
            throttle.max_uploads.global.set = 250
            throttle.max_uploads.set = 100
            throttle.min_peers.normal.set = 20
            throttle.min_peers.seed.set = 30
            trackers.numwant.set = 80
            trackers.use_udp.set = no
            print = (cat, "Logging to ", (cfg.logfile))
            log.open_file = "log", (cfg.logfile)
            log.add_output = "info", "log"

    initContainers:
      remove-session-lock:
        command:
          - sh
          - '-c'
        args:
          - 'rm -rf /config/.local/share/rtorrent/.session/rtorrent.lock && chown -vR 1001:1001 /config'
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: config
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    service:
      main:
        ports:
          http:
            port: 3000

      bittorrent:
        enabled: true
        ports:
          bittorrent:
            port: 15329
            targetPort: 15329
        annotations:
          metallb.universe.tf/allow-shared-ip: "metallb-shared-ip"
        type: LoadBalancer
        externalIPs:
          - ${METALLB_ADDRESS}
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: torrent.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        size: 1Gi
        retain: true
      rtorrent-flood-config:
        enabled: true
        type: configMap
        mountPath: /config/.rtorrent.rc
        subPath: .rtorrent.rc
        name: rtorrent-flood-config
      downloads:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Downloads/Complete
        mountPath: /downloads/complete
      ebook:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Downloads/Ebook
        mountPath: /downloads/ebook
      games:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Downloads/Games
        mountPath: /downloads/games
      program:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Downloads/Program
        mountPath: /downloads/program
      movies:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Media/Movies/Downloads
        mountPath: /downloads/movies
      shows:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Media/Shows/Downloads
        mountPath: /downloads/shows
      music:
        enabled: true
        type: nfs
        server: nas
        path: /tank/Media/Music/Downloads
        mountPath: /downloads/music


    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 3Gi
        cpu: 50m
