---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - middlewares.yaml
  - release-recorder.yaml
  - release-frontend.yaml
  - alerts.yaml
configMapGenerator:
  - name: owntracks-frontend
    namespace: owntracks
    files:
      - config.js
  - name: owntracks-recorder
    namespace: owntracks
    files:
      - hook.lua
secretGenerator:
  - name: owntracks-recorder
    namespace: owntracks
    envs:
      - secrets.sops.env
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: owntracks-recorder-basic-auth
    namespace: owntracks
    type: kubernetes.io/basic-auth
    envs:
      - basic-auth.sops.env
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
