---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - middlewares.yaml
  - release-frontend.yaml
configMapGenerator:
  - name: owntracks-frontend
    namespace: owntracks
    files:
      - config.js
configurations:
  - kustomizeconfig.yaml
