---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: recorder-basic-auth
  namespace: owntracks
spec:
  basicAuth:
    secret: owntracks-recorder-basic-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: recorder-path-replace
  namespace: owntracks
spec:
  replacePath:
    path: /pub
