apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owntracks-recorder
  namespace: owntracks
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          priorityClassName: public
        containers:
          main:
            env:
              OTR_CAPATH: /etc/ssl/certs/
              OTR_LUASCRIPT: /config/hook.lua
              OTR_HOST: "mqtt.${DOMAIN_LOCAL}"
              OTR_PORT: 8883
              OTR_HTTPHOST: 0.0.0.0
              OTR_TOPICS: "owntracks/#"
              OTR_USER: owntracks
              TZ: ${TZ}
            envFrom:
              - secretRef:
                  name: owntracks-recorder
            image:
              repository: docker.io/owntracks/recorder
              tag: 0.9.8 # {"$imagepolicy": "flux-system:owntracks-recorder:tag"}
            nameOverride: owntracks-recorder
            ports:
              - containerPort: 8083
                name: http
                protocol: TCP
            securityContext:
              capabilities:
                drop:
                  - ALL
            resources:
              limits:
                memory: 64Mi
              requests:
                cpu: 1m
                memory: 45Mi
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:record-rec
          hajimari.io/appName: Recorder
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: otr.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
      public:
        annotations:
          hajimari.io/enable: "false"
          traefik.ingress.kubernetes.io/router.entrypoints: webpublic
          traefik.ingress.kubernetes.io/router.middlewares: owntracks-recorder-path-replace@kubernetescrd,owntracks-recorder-basic-auth@kubernetescrd
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: otr.${DOMAIN_PUBLIC}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /config/hook.lua
            subPath: hook.lua
        name: owntracks-recorder
        type: configMap
      data:
        accessMode: ReadWriteOnce
        enabled: true
        globalMounts:
          - path: /store
        retain: true
        size: 1Gi
        storageClass: longhorn
    service:
      main:
        ports:
          http:
            port: 8083
