apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owntracks-frontend
  namespace: owntracks
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.2.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        containers:
          main:
            env:
              LISTEN_PORT: 8080
              SERVER_HOST: owntracks-recorder
              SERVER_PORT: 8083
              TZ: ${TZ}
            image:
              repository: docker.io/owntracks/frontend
              tag: 2.12.0 # {"$imagepolicy": "flux-system:owntracks-frontend:tag"}
            nameOverride: owntracks-frontend
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - CHOWN
                  - SETGID
                  - SETUID
            resources:
              limits:
                memory: 32Mi
              requests:
                cpu: 10m
                memory: 4Mi
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:radar
          hajimari.io/appName: Owntracks
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        labels:
          probe: enabled
        hosts:
          - host: owntracks.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /usr/share/nginx/html/config/config.js
            subPath: config.js
        name: owntracks-frontend
        type: configMap
    service:
      main:
        ports:
          http:
            port: 8080
