---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: owntracks-frontend
  namespace: owntracks
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.5.0  # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/owntracks/frontend
      tag: 2.12.0  # {"$imagepolicy": "flux-system:owntracks-frontend:tag"}
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - CHOWN
          - SETGID
          - SETUID
    env:
      LISTEN_PORT: 8080
      SERVER_HOST: owntracks-recorder
      SERVER_PORT: 8083
    ingress:
      main:
        enabled: true
        annotations:
          hajimari.io/icon: mdi:radar
          hajimari.io/appName: Owntracks
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: owntracks.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    service:
      main:
        ports:
          http:
            port: 8080
    persistence:
      config:
        enabled: true
        type: configMap
        name: owntracks-frontend
        mountPath: /usr/share/nginx/html/config/config.js
        subPath: config.js
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 4Mi
