---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: grocy
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: grocy
      namespace: grocy
  providerRef:
    name: alertmanager
