apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: grocy
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.0.3 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/grocy/frontend
      tag: "v4.0.3" # {"$imagepolicy": "flux-system:grocy-frontend:tag"}
      pullPolicy: IfNotPresent
    env: {}
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsUser: 82
      runAsGroup: 82
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: grocy.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: false
      tmp:
        enabled: true
        type: emptyDir
        mountPath: /tmp
        medium: Memory
    resources:
      limits:
        memory: 32Mi
      requests:
        cpu: 10m
        memory: 8Mi
