apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: grocy
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.1.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 82
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            args:
              - 'cp /var/www/data/config.php /config/config.php && php-fpm82'
            command:
              - sh
              - '-c'
            env:
              GROCY_CALENDAR_FIRST_DAY_OF_WEEK: '1'
              GROCY_CURRENCY: HUF
              GROCY_DATAPATH: /config
              GROCY_FEATURE_FLAG_BATTERIES: 'false'
              GROCY_FEATURE_FLAG_CALENDAR: 'false'
              GROCY_FEATURE_FLAG_CHORES: 'false'
              GROCY_FEATURE_FLAG_TASKS: 'false'
              TZ: ${TZ}
            image:
              repository: docker.io/grocy/backend
              tag: "v4.2.0" # {"$imagepolicy": "flux-system:grocy-backend:tag"}
              pullPolicy: IfNotPresent
            nameOverride: backend
            ports:
              - containerPort: 9000
                name: http
                protocol: TCP
            securityContext:
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsUser: 82
              runAsGroup: 82
            resources:
              limits:
                memory: 64Mi
              requests:
                cpu: 10m
                memory: 32Mi
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        mountPath: /config
        retain: true
        size: 1Gi
        storageClass: longhorn
      tmp:
        enabled: true
        medium: Memory
        type: emptyDir
      viewcache:
        enabled: true
        globalMounts:
          - path: /config/viewcache
        medium: Memory
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 9000
