---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: backend
  namespace: grocy
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.5.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    initContainers:
      create-config-folders:
        command:
          - sh
          - '-c'
          - chown -R 82:82 /config
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: config
    image:
      repository: docker.io/grocy/backend
      tag: "v4.0.3" # {"$imagepolicy": "flux-system:grocy-backend:tag"}
      pullPolicy: IfNotPresent
    command:
      - sh
      - '-c'
    args:
      - 'cp /var/www/data/config.php /config/config.php && php-fpm81'
    env:
      GROCY_DATAPATH: /config
      GROCY_CALENDAR_FIRST_DAY_OF_WEEK: '1'
      GROCY_CURRENCY: HUF
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsUser: 82
      runAsGroup: 82
    service:
      main:
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        size: 1Gi
        retain: true
      tmp:
        enabled: true
        type: emptyDir
        mountPath: /tmp
        medium: Memory
      viewcache:
        enabled: true
        type: emptyDir
        mountPath: /config/viewcache
        medium: Memory
    resources:
      limits:
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
