apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frontend
  namespace: grocy
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.6.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 82
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            env:
              TZ: ${TZ}
            image:
              repository: docker.io/grocy/frontend
              tag: "v4.0.3" # {"$imagepolicy": "flux-system:grocy-frontend:tag"}
              pullPolicy: IfNotPresent
            nameOverride: frontend
            ports:
              - containerPort: 8080
                name: http
                protocol: TCP
            securityContext:
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsUser: 82
              runAsGroup: 82
            resources:
              limits:
                memory: 32Mi
              requests:
                cpu: 1m
                memory: 16Mi
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:cart
          hajimari.io/appName: Grocy
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: grocy.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: false
      tmp:
        enabled: true
        medium: Memory
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 8080
