---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: tf-controller
      namespace: flux-system
  providerRef:
    name: alertmanager
