---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: tf-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      version: 0.15.1
