---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - alerts.yaml
  - tf-auth-db.yaml
  - seed.yaml

configMapGenerator:
  - name: seed-script
    namespace: emqx-operator-system
    files:
      - seed.sql

secretGenerator:
  - name: emqx-auth
    namespace: emqx-operator-system
    files:
      - acl.csv=acl.sops.csv
      - user.csv=user.sops.csv
  - name: core-db-terraform
    namespace: emqx-operator-system
    options:
      disableNameSuffixHash: true
    envs:
      - ../cnpg/tf-user.sops.env

generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled

configurations:
  - kustomizeconfig.yaml
