---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: emqx-operator-system
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: emqx-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: emqx-operator-system
      version: 2.2.5
