---
apiVersion: batch/v1
kind: Job
metadata:
  name: seed-auth
  namespace: emqx-operator-system
  labels:
    kustomize.toolkit.fluxcd.io/force: enabled
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: seed-emqx-auth
          image: docker.io/postgres:16-alpine
          command:
            - psql
          args:
            - --echo-all
            - --no-psqlrc
            - --pset=pager=off
            - --variable=ON_ERROR_STOP=1
            - --file=/seed.sql
          env:
            - name: PGDATABASE
              valueFrom:
                secretKeyRef:
                  name: auth-db-emqx
                  key: EMQX_AUTHENTICATION__1__DATABASE

            - name: PGHOST
              value: core-db-rw.cnpg-system
            - name: PGOPTIONS
              value: --client-min-messages=warning
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-db-emqx
                  key: EMQX_AUTHENTICATION__1__PASSWORD
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: auth-db-emqx
                  key: EMQX_AUTHENTICATION__1__USERNAME
            - name: TZ
              value: ${TZ}
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /acl.csv
              name: emqx-auth
              readOnly: true
              subPath: acl.csv
            - mountPath: /user.csv
              name: emqx-auth
              readOnly: true
              subPath: user.csv
            - mountPath: /seed.sql
              name: script
              readOnly: true
              subPath: seed.sql
      restartPolicy: Never
      volumes:
        - name: emqx-auth
          secret:
            secretName: emqx-auth
        - name: script
          configMap:
            name: seed-script
