---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: metallb
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: metallb
      namespace: metallb-system
  providerRef:
    name: alertmanager
