apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tdarr
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            nameOverride: tdarr
            env:
              PGID: 997
              PUID: 929
              TZ: ${TZ}
              UMASK_SET: "002"
              ffmpegVersion: 6
              inContainer: "true"
              internalNode: "false"
              nodeName: Coordinator
              serverIP: 0.0.0.0
              serverPort: 8266
              webUIPort: 8265
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/haveagitgat/tdarr
              tag: 2.26.01 # {"$imagepolicy": "flux-system:tdarr:tag"}
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
                drop:
                  - ALL
              readOnlyRootFilesystem: false
            ports:
              - containerPort: 8265
                name: http
                protocol: TCP
              - containerPort: 8266
                name: coordinator
                protocol: TCP
            resources:
              limits:
                memory: 2Gi
              requests:
                cpu: 1
                memory: 1500Mi
      node:
        enabled: true
        type: statefulset
        replicas: 1
        rollingUpdate:
          partition: 0
        statefulset:
          podManagementPolicy: OrderedReady
        pod:
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 105
        containers:
          tdarr-node:
            env:
              PGID: 997
              PUID: 929
              TZ: ${TZ}
              UMASK_SET: "002"
              ffmpegVersion: 6
              inContainer: "true"
              serverIP: tdarr-coordinator
              serverPort: 8266
              nodeName:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            image:
              pullPolicy: IfNotPresent
              repository: ghcr.io/andrasmaroy/tdarr_node
              tag: 2.15.01 # {"$imagepolicy": "flux-system:tdarr-node:tag"}
            resources:
              limits:
                gpu.intel.com/i915: 1
                memory: 8Gi
              requests:
                cpu: 1
                memory: 6Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - CHOWN
                  - SETUID
                  - SETGID
                drop:
                  - ALL
              readOnlyRootFilesystem: false
              runAsGroup: 997
    ingress:
      main:
        annotations:
          hajimari.io/icon: simple-icons:ffmpeg
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: tdarr.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        advancedMounts:
          main:
            main:
              - path: /app/server
        globalMounts: []
        retain: true
        size: 5Gi
        storageClass: longhorn
      movies:
        enabled: true
        mountPath: /media/movies
        path: /tank/Media/Movies
        server: nas
        type: nfs
      shows:
        enabled: true
        mountPath: /media/shows
        path: /tank/Media/Shows
        server: nas
        type: nfs
    service:
      main:
        ports:
          http:
            port: 8265
      coordinator:
        controller: main
        ports:
          coordinator:
            port: 8266
            protocol: TCP
