---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: longhorn
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: longhorn
      namespace: longhorn-system
  providerRef:
    name: alertmanager
