---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      version: 1.4.0
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: true
    ingress:
      enabled: true
      host: longhorn.kubi.${DOMAIN_LOCAL}
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
