---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: service-replicated-longhorn
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  numberOfReplicas: "1"
  dataLocality: "best-effort"
  staleReplicaTimeout: "2880"  # 48 hours in minutes
  fromBackup: ""
