---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 2.0.3  # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {}  # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            nameOverride: sonarr
            env:
              ANALYTICS: "false"
              SGID: 997
              TZ: ${TZ}
            image:
              pullPolicy: IfNotPresent
              repository: docker.io/spritsail/sonarr
              tag: 4.0.1
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - SETUID
                  - SETGID
                drop:
                  - ALL
              readOnlyRootFilesystem: false
            ports:
              - containerPort: 8989
                name: http
                protocol: TCP
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - 'wget -qO /dev/null http://127.0.0.1:8989/api/system/status?apiKey=`xmlstarlet sel -t -v /Config/ApiKey /config/config.xml`'
                  initialDelaySeconds: 60
                  timeoutSeconds: 5
            resources:
              limits:
                memory: 600Mi
              requests:
                cpu: 10m
                memory: 400Mi
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:television-box
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: sonarr.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled

    persistence:
      config:
        enabled: true
        mountPath: /config
        retain: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        mountPath: /media
        path: /tank/Media/Shows
        server: nas
        type: nfs

    service:
      main:
        ports:
          http:
            port: 8989
