---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: hass
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: hass
      namespace: home-automation
  providerRef:
    name: alertmanager
