---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  image: docker.io/homeassistant/home-assistant
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: home-assistant
  policy:
    semver:
      range: '*'
