---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - image-updates.yaml
  - alerts.yaml

secretGenerator:
  - name: home-assistant
    namespace: home-automation
    files:
      - secrets.yaml=secrets.sops.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
