apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hass
  namespace: home-automation
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.1.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
        containers:
          main:
            env:
              S6_READ_ONLY_ROOT: 1
              TZ: ${TZ}
            image:
              repository: docker.io/homeassistant/home-assistant
              tag: "2024.4.3" # {"$imagepolicy": "flux-system:home-assistant:tag"}
              pullPolicy: IfNotPresent
            nameOverride: hass
            ports:
              - containerPort: 5683
                name: coiot
                protocol: UDP
              - containerPort: 8123
                name: http
                protocol: TCP
            resources:
              limits:
                memory: 1400Mi
              requests:
                memory: 1Gi
                cpu: 50m
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - NET_RAW
              readOnlyRootFilesystem: true
        initContainers:
          get-hacs:
            command:
              - '/bin/bash'
              - '-c'
            args:
              - '[ ! -f /config/.HA_VERSION ] && echo 2023.7.3 > /config/.HA_VERSION; if [ ! -d /config/custom_components/hacs ]; then wget -O - https://get.hacs.xyz | bash -; fi'
            image:
              repository: docker.io/vandot/alpine-bash
              tag: latest
            securityContext:
              runAsUser: 0
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:home-assistant
          hajimari.io/appName: Home Assistant
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: hass.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        retain: true
        size: 1Gi
        storageClass: longhorn
      run:
        enabled: true
        medium: Memory
        type: emptyDir
      secrets:
        advancedMounts:
          main:
            main:
              - path: /config/secrets.yaml
                readOnly: true
                subPath: secrets.yaml
        enabled: true
        globalMounts: []
        name: home-assistant
        type: secret
    service:
      main:
        ports:
          http:
            port: 8123
      coiot:
        annotations:
          metallb.universe.tf/allow-shared-ip: "metallb-shared-ip"
        controller: main
        enabled: true
        externalIPs:
          - ${METALLB_ADDRESS}
        ports:
          coiot:
            enabled: true
            primary: false
            port: 5683
            targetPort: 5683
            protocol: UDP
        primary: false
        type: LoadBalancer
