sendgrid_apikey: ENC[AES256_GCM,data:9FxaCs1wkY5MHxv5I7plZzL7NDRzKdvlM48zbCQcf5sTXuZ+WWa9ic87tpUkAw/u0l8J1OyrBukChtfGBHPJ+FzhDbX7,iv:7L3IIO9Nje/+wIEWfWiX+U2Mk9KY4u9vu/uyPXOoscc=,tag:nb08QSVoXVG+KS48ZZDStQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-05T09:03:06Z"
    mac: ENC[AES256_GCM,data:VdOX5clY+P2fneu782A5+OM4q8OP2DpFUnA3FamrY0xbbeEhAr+TrvRdl+wAxTLI91AhcK2Ay1E7kCFDcRRtXoaG1zulfRIrksp4BoXBt1Z+mz3uOfBW7oj/jS4bzFMcIEztGiGxrevx+CShfrayFVBfNCgYdfzYSRxiXJzwbko=,iv:uyAjb9TNuBCfUwq2kmXvG/OuVFPKa7+tkx6DF5wHKF4=,tag:aCZ1YUluKWT2rOK95pmSZQ==,type:str]
    pgp:
        - created_at: "2023-02-05T09:02:56Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/2zKbmHCsRnAQ//X3y9Yied5dggMmJzDUk8wFX/6X9sCy2sjhgg9lvcrlWy
            Ep4wC/c/5mfj/YnNwPkNTHvNinGo4akps+vZMrw7eOXhcJdFULzHJV+oxog0Dc1M
            ZZHocL9ytBRYzJNtCUxGSdybe4TRdIM2+KCnOjGxrmF3O8iEAaFOePtZnhIHAPuA
            7HbjcYgnCBBONCBafX1mGWnLs8S/wk8ZJo4y9ojhGfDvae/kjBJtM9nWB2ohYIyW
            eBXokHHok5pfuVwshInaaD1VF/uyPoDJWfoYuDelMO03TDB9tirXay10Wyr61Dct
            GJcz+HAFLnT2lluFyPbM6gnpNzUlettHbjLJEZZ/5DnyBp3CWSHC0cD6KrF+wnMY
            gYU1RXOOm9Iy9TT1GEFQD6x33tuW846X6r/ClMfOUJpIM2PrFMGLA0i9wXHydb6G
            6PWK29FLEGQuMoOMxTlZoUKE8gBD3ScaJ759/8zsdt6zQtRFXKGlRqp2hxyxGVOL
            M3Cz00mHKkrh+RL6Ek6i4L2CpzqKEye/fw7Y6LS7vi9XP8d8o6jG0grQi+1pxTm5
            qrAkv2JdgzcAiTRdHv/wTDCJaeEzAHzYCMh61lT1s1ALQBjR/GBAPd7DLkZBtqyj
            KCfudRaqZhJzDZ48/z2MPxWhJcJEaodrrBvRSD5oe9Ure2CQTG6DPpxmYnf9/x7S
            XgFlgQs6DIJsBYKUEJ/7L+nrJ8i+usIcOQTheOvZIcf31iobRIC8m0nIdLOBbw6J
            Qbg81NpdqttGsCtwe/jbEgUgiHdYixlmCympTv3wSLfi74gxdtlqGBBPCGH54MI=
            =pVDn
            -----END PGP MESSAGE-----
          fp: 976AA83A5066FFE4CF485376F76C07C5F5BB0BEB
    unencrypted_suffix: _unencrypted
    version: 3.7.3
