apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.7.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            env:
              SGID: 997
              TZ: ${TZ}
            image:
              repository: docker.io/spritsail/jackett
              tag: "0.22.1355" # {"$imagepolicy": "flux-system:jackett:tag"}
              pullPolicy: IfNotPresent
            nameOverride: jackett
            ports:
              - containerPort: 9117
                name: http
                protocol: TCP
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - wget
                      - -qO
                      - /dev/null
                      - http://localhost:9117/torznab/all
                  initialDelaySeconds: 10
                  timeoutSeconds: 5
            resources:
              limits:
                memory: 210Mi
              requests:
                memory: 172Mi
                cpu: 3m
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - SETUID
                  - SETGID
              readOnlyRootFilesystem: true
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:movie-search
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: jackett.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        mountPath: /config
        retain: true
        size: 1Gi
        storageClass: longhorn
      tmp:
        enabled: true
        mountPath: /tmp
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 9117
