apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 1.3.2 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    image:
      repository: docker.io/spritsail/jackett
      tag: "0.20.3678" # {"$imagepolicy": "flux-system:jackett:tag"}
      pullPolicy: IfNotPresent
    env:
      SUID: 568
      SGID: 568
    probes:
      liveness:
        custom: true
        spec:
          exec:
            command:
              - wget
              - -qO
              - /dev/null
              - http://localhost:9117/torznab/all
          initialDelaySeconds: 10
          timeoutSeconds: 5
    securityContext:
      capabilities:
        drop:
          - ALL
        add:
          - SETUID
          - SETGID
    service:
      main:
        ports:
          http:
            port: 9117
    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - host: jackett.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        mountPath: /config
        storageClass: longhorn
        size: 1Gi
        retain: true
    resources:
      limits:
        memory: 400Mi
      requests:
        memory: 200Mi
        cpu: 10m
