---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: nexus
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: nexus
      namespace: nexus
  providerRef:
    name: alertmanager
