---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - auth.sops.yaml
  - repository.yaml
  - release.yaml
  - cronjob.yaml
  - alerts.yaml
  - image-updates.yaml

configMapGenerator:
  - files:
      - repo-cleanup.sh=repo-cleanup.sh
    name: repo-cleanup
    namespace: nexus
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
      disableNameSuffixHash: true
