---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: nexus3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: nexus
      version: 5.10.0   # {"$imagepolicy": "flux-system:nexus-chart:tag"}
  values:
    bashImage:
      repository: docker.io/bash
    service:
      additionalPorts:
        - port: 8082
          name: dockerio
          containerPort: 8082
          hosts:
            - nexus-dockerio.kubi.${DOMAIN_LOCAL}
        - port: 8083
          name: ghcrio
          containerPort: 8083
          hosts:
            - nexus-ghcrio.kubi.${DOMAIN_LOCAL}
        - port: 8084
          name: quayio
          containerPort: 8084
          hosts:
            - nexus-quayio.kubi.${DOMAIN_LOCAL}
    ingress:
      enabled: true
      hosts:
        - nexus.kubi.${DOMAIN_LOCAL}
      annotations:
        hajimari.io/icon: simple-icons:sonatype
        hajimari.io/group: foundation
        hajimari.io/appName: nexus
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

    env:
      - name: TZ
        value: ${TZ}

    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi

    resources:
      limits:
        memory: 4Gi
      requests:
        cpu: 150m
        memory: 3Gi

    rootPassword:
      secret: nexus-auth

    config:
      enabled: true
      anonymous:
        enabled: true
      realms:
        enabled: true
        values:
          - DockerToken
          - NexusAuthenticatingRealm
      repos:
        - name: docker.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://registry-1.docker.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8082
          dockerProxy:
            indexType: HUB
            cacheForeignLayers: false
        - name: ghcr.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://ghcr.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8083
          dockerProxy:
            indexType: REGISTRY
            cacheForeignLayers: false
        - name: quay.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://quay.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8084
          dockerProxy:
            indexType: REGISTRY
            cacheForeignLayers: false
        - name: cnpg
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://cloudnative-pg.github.io/charts
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: emqx
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://repos.emqx.io/charts
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: tf-controller
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://flux-iac.github.io/tofu-controller
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: hajimari
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://hajimari.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: traefik
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://helm.traefik.io/traefik
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: kubernetes-dashboard
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://kubernetes.github.io/dashboard
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: longhorn
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://charts.longhorn.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: metallb
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://metallb.github.io/metallb
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
        - name: gissilabs
          format: helm
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://gissilabs.github.io/charts/
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
