---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: nexus3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
        namespace: nexus
      version: 5.10.0
  values:
    bashImage:
      repository: docker.io/bash
    ingress:
      enabled: true
      hosts:
        - nexus.kubi.${DOMAIN_LOCAL}
      annotations:
        hajimari.io/icon: simple-icons:sonatype
        hajimari.io/group: foundation
        hajimari.io/appName: nexus
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"

    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi

    rootPassword:
      secret: nexus-auth

    config:
      enabled: true
      anonymous:
        enabled: true
      realms:
        enabled: true
        values:
          - DockerToken
          - NexusAuthenticatingRealm
      repos:
        - name: docker.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://registry-1.docker.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8082
          dockerProxy:
            indexType: HUB
            cacheForeignLayers: false
        - name: ghcr.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://ghcr.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8083
          dockerProxy:
            indexType: REGISTRY
            cacheForeignLayers: false
        - name: quay.io
          format: docker
          type: proxy
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
          proxy:
            remoteUrl: https://quay.io
            contentMaxAge: -1
            metadataMaxAge: 1440
          negativeCache:
            enabled: false
            timeToLive: 1440
          httpClient:
            blocked: false
            autoBlock: true
          docker:
            v1Enabled: false
            forceBasicAuth: false
            httpPort: 8084
          dockerProxy:
            indexType: REGISTRY
            cacheForeignLayers: false
