---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/intel/intel-device-plugins-for-kubernetes.git
  ref:
    tag: v0.24.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: intel-gpu-plugin
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: kube-system
  sourceRef:
    kind: GitRepository
    name: intel-gpu-plugin
  path: "./deployments/gpu_plugin"
  prune: true
  timeout: 15m0s
