apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          priorityClassName: public
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 44
              - 105
        containers:
          main:
            env:
              TZ: ${TZ}
            image:
              repository: docker.io/jellyfin/jellyfin
              tag: 10.10.3 # {"$imagepolicy": "flux-system:jellyfin:tag"}
              pullPolicy: IfNotPresent
            nameOverride: jellyfin
            ports:
              - containerPort: 8096
                name: http
                protocol: TCP
              - containerPort: 8920
                name: https
                protocol: TCP
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/bash
                      - '-c'
                      - 'curl -Lk -fsS http://127.0.0.1:8096/health || exit 1'
                  initialDelaySeconds: 10
                  periodSeconds: 30
                  timeoutSeconds: 30
              readiness:
                type: HTTP
                path: /
            resources:
              limits:
                gpu.intel.com/i915: 1
                memory: 6Gi
              requests:
                memory: 2Gi
                cpu: 1
            securityContext:
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              runAsGroup: 997
              runAsNonRoot: true
              runAsUser: 942
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:emby
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: jelly.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
      public:
        annotations:
          hajimari.io/enable: "false"
          traefik.ingress.kubernetes.io/router.entrypoints: webpublic
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: play.${DOMAIN_PUBLIC}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        retain: true
        size: 20Gi
        storageClass: longhorn
      media:
        enabled: true
        globalMounts:
          - path: /mnt/tv
            subPath: Shows/Complete
          - path: /mnt/movies
            subPath: Movies/Complete
          - path: /jellyfin/jellyfin-web/main.jellyfin.bundle.js
            subPath: main.jellyfin.bundle.js
        path: /tank/Media
        server: nas
        type: nfs
      certificate:
        enabled: true
        globalMounts:
          - path: /etc/ssl/private
            readOnly: true
        name: letsencrypt-jellyfin
        type: secret
      cache:
        enabled: true
        mountPath: /cache
        type: emptyDir
      tmp:
        enabled: true
        mountPath: /tmp
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 8096
      https:
        annotations:
          metallb.universe.tf/allow-shared-ip: "metallb-shared-ip"
        controller: main
        enabled: true
        externalIPs:
          - ${METALLB_ADDRESS}
        ports:
          https:
            port: 8920
        type: LoadBalancer
    serviceAccount:
      create: true
