---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
secretGenerator:
  - name: tailscale-auth
    namespace: tailscale
    envs:
      - secrets.sops.env
