---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - sa.yaml
  - release.yaml
  - image-updates.yaml
secretGenerator:
  - name: tailscale-auth
    namespace: tailscale
    envs:
      - secrets.sops.env
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
