apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: subnet-router
  namespace: tailscale
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.1 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          priorityClassName: public
        type: statefulset
        containers:
          main:
            env:
              TS_ACCEPT_DNS: "false"
              TS_AUTHKEY:
                valueFrom:
                  secretKeyRef:
                    name: tailscale-auth
                    key: TS_AUTHKEY
              TS_EXTRA_ARGS: "--advertise-exit-node"
              TS_KUBE_SECRET: subnet-router
              TS_ROUTES:
                valueFrom:
                  secretKeyRef:
                    name: tailscale-auth
                    key: TS_ROUTES
              TS_USERSPACE: "true"
              TZ: ${TZ}
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: "v1.78.3" # {"$imagepolicy": "flux-system:tailscale:tag"}
              pullPolicy: IfNotPresent
            nameOverride: subnet-router
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - "tailscale --socket=/tmp/tailscaled.sock status --peers=false --active=true --json | grep -q '^    \"Online\": true,$'"
                  initialDelaySeconds: 60
                  timeoutSeconds: 5
            resources:
              limits:
                memory: 128Mi
              requests:
                cpu: 25m
                memory: 64Mi
            securityContext:
              readOnlyRootFilesystem: true
              runAsGroup: 1000
              runAsUser: 1000
    persistence:
      cache:
        enabled: true
        globalMounts:
          - path: /.cache
        medium: Memory
        type: emptyDir
      tmp:
        enabled: true
        type: emptyDir
    service:
      main:
        enabled: false
    serviceAccount:
      name: tailscale
