---
apiVersion: v1
stringData:
  address: http://alertmanager-operated.monitoring.svc.cluster.local:9093/api/v2/alerts/
kind: Secret
metadata:
  name: alertmanager-address
  namespace: flux-system
type: Opaque
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  type: alertmanager
  secretRef:
    name: alertmanager-address
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  providerRef:
    name: alertmanager
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
