---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  providerRef:
    name: alertmanager
