---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: cert-manager-chart
  namespace: flux-system
spec:
  image: quay.io/jetstack/charts/cert-manager
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: cert-manager-chart
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: cert-manager-chart
  policy:
    semver:
      range: '*'
