---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cluster-issuer.yaml
  - alerts.yaml
  - image-updates.yaml

secretGenerator:
  - name: cloudflare-api-key
    namespace: cert-manager
    envs:
      - secrets.sops.env
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
