---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: omada
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: omada
      namespace: networking
  providerRef:
    name: alertmanager
