---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: omada
  namespace: flux-system
spec:
  image: docker.io/mbentley/omada-controller
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: omada
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: omada
  filterTags:
    pattern: '^(?P<major>\d+)\.(?P<minor>\d+)$'
    extract: '$major.$minor'
  policy:
    semver:
      range: '*'
