---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - certificate.yaml
  - release.yaml
  - alerts.yaml
secretGenerator:
  - name: vernemq-auth
    namespace: vernemq
    files:
      - vernemq-passwd=users.sops
      - vernemq-acl=acl.sops
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configurations:
  - kustomizeconfig.yaml
