---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: vernemq
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: vernemq
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vernemq
        namespace: vernemq
      version: 1.9.0
  values:
    replicaCount: 3
    additionalEnv:
      - name: DOCKER_VERNEMQ_ACCEPT_EULA
        value: 'yes'
      - name: DOCKER_VERNEMQ_LISTENER__SSL__CAFILE
        value: "/etc/ssl/vernemq/tls.crt"
      - name: DOCKER_VERNEMQ_LISTENER__SSL__CERTFILE
        value: "/etc/ssl/vernemq/tls.crt"
      - name: DOCKER_VERNEMQ_LISTENER__SSL__KEYFILE
        value: "/etc/ssl/vernemq/tls.key"
    extraVolumes:
      - name: vernemq-auth
        secret:
          secretName: vernemq-auth
          defaultMode: 420
    extraVolumeMounts:
      - name: vernemq-auth
        mountPath: /etc/vernemq/vmq.acl
        subPath: vernemq-acl
        readOnly: true
      - name: vernemq-auth
        mountPath: /etc/vernemq/vmq.passwd
        subPath: vernemq-passwd
        readOnly: true
    resources:
      requests:
        cpu: 25m
        memory: 512Mi
      limits:
        memory: 76Mi
    secretMounts:
      - name: vernemq-certificates
        secretName: letsencrypt-vernemq
        path: /etc/ssl/vernemq
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: "metallb-shared-ip"
      externalIPs:
        - ${METALLB_ADDRESS}
      type: LoadBalancer
      mqtt:
        enabled: false
      mqtts:
        enabled: true
