---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vernemq
  namespace: vernemq
spec:
  interval: 1m0s
  timeout: 15m0s
  chart:
    spec:
      chart: vernemq
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: vernemq
        namespace: vernemq
      version: 1.9.0
  values:
    replicaCount: 3
    additionalEnv:
      - name: DOCKER_VERNEMQ_ACCEPT_EULA
        value: 'yes'
    extraVolumes:
      - name: vernemq-auth
        secret:
          secretName: vernemq-auth
          defaultMode: 420
    extraVolumeMounts:
      - name: vernemq-auth
        mountPath: /etc/vernemq/vmq.acl
        subPath: vernemq-acl
        readOnly: true
      - name: vernemq-auth
        mountPath: /etc/vernemq/vmq.passwd
        subPath: vernemq-passwd
        readOnly: true
    resources:
      requests:
        cpu: 25m
        memory: 256Mi
      limits:
        memory: 384Mi
