---

- name: Update apt cache
  apt:
    cache_valid_time: 86400
  ignore_errors: yes

- name: Configure SSH config.
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '{{ item.regexp }}'
    line: '{{ item.line }}'
    state: present
  with_items:
    - regexp: '^#?PermitRootLogin'
      line: 'PermitRootLogin no'
    - regexp: '^#?PermitEmptyPasswords'
      line: 'PermitEmptyPasswords no'
    - regexp: '^#?PasswordAuthentication'
      line: 'PasswordAuthentication no'
  register: sshd_config_changed

- name: Restart SSHD if needed
  systemd:
    name: ssh
    state: restarted
  when: sshd_config_changed.changed
