{
 "title": "Kubernetes / Compute resources / Rightsizing",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{job=\"kube-state-metrics\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource requests / limits",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod, container) (kube_pod_container_info{container!=\"\",namespace=~\"$namespace\"}) unless sum by (namespace, pod, container) (kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod, container) (kube_pod_container_info{container!=\"\",namespace=~\"$namespace\"}) unless sum by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"})\nunless\nsum by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (namespace, pod, container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory usage (request %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m])) / (sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage outliers (high)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m])) / (sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))) * 100 > (100 + 100 / 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage outliers (low)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m])) / (sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))) * 100 < (2 * 100 / 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage outliers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[$__range])) / (sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (avg_over_time(container_memory_working_set_bytes{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[$__range])) / (sum by (cluster, namespace, pod, container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"memory\",namespace=~\"$namespace\"}))) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (max_over_time(container_memory_working_set_bytes{container!=\"\",image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU usage (request %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, namespace, pod, container) (\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n    )\n  )\n/\n  (\n    sum by (cluster, namespace, pod, container) (\n        kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}\n    )\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage outliers (high)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, namespace, pod, container) (\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n    )\n  )\n/\n  (\n    sum by (cluster, namespace, pod, container) (\n        kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}\n    )\n  )\n) * 100 > (100 + 100 / 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage outliers (low)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, namespace, pod, container) (\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n    )\n  )\n/\n  (\n    sum by (cluster, namespace, pod, container) (\n        kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}\n    )\n  )\n) * 100 < (2 * 100 / 3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage outliers",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, namespace, pod, container) (\n    avg_over_time (\n      rate(\n        container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n      )[$__range:15m]\n    )\n  )\n/\n  (\n    sum by (cluster, namespace, pod, container) (\n        kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}\n    )\n  )\n) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (cluster, namespace, pod, container) (\n  avg_over_time (\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n    )[$__range:15m]\n  )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (kube_pod_container_resource_requests{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (cluster, namespace, pod, container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum by (cluster, namespace, pod, container) (\n    avg_over_time (\n      rate(\n        container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n      )[$__range:15m]\n    )\n  )\n/\n  (\n    sum by (cluster, namespace, pod, container) (\n        kube_pod_container_resource_limits{job=\"kube-state-metrics\",resource=\"cpu\",namespace=~\"$namespace\"}\n    )\n  )\n) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (cluster, namespace, pod, container) (\n  max_over_time (\n    rate(\n      container_cpu_usage_seconds_total{image!=\"\",job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",namespace=~\"$namespace\"}[15m]\n    )[$__range:15m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}