apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 1m0s
  chart:
    spec:
      chart: app-template
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      version: 3.5.0 # {"$imagepolicy": "flux-system:app-template:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    controllers:
      main:
        pod:
          securityContext:
            fsGroup: 997
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          main:
            env:
              ANALYTICS: "false"
              SGID: 997
              TZ: ${TZ}
            image:
              repository: docker.io/spritsail/radarr
              tag: "5.12.0" # {"$imagepolicy": "flux-system:radarr:tag"}
              pullPolicy: IfNotPresent
            nameOverride: radarr
            ports:
              - containerPort: 7878
                name: http
                protocol: TCP
            probes:
              liveness:
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - '-c'
                      - 'wget -qO /dev/null http://localhost:7878/api/v3/system/status?apiKey=`xmlstarlet sel -t -v /Config/ApiKey /config/config.xml`'
                  initialDelaySeconds: 60
                  timeoutSeconds: 5
            resources:
              limits:
                memory: 512Mi
              requests:
                memory: 256Mi
                cpu: 10m
            securityContext:
              capabilities:
                drop:
                  - ALL
                add:
                  - SETUID
                  - SETGID
              readOnlyRootFilesystem: true
    ingress:
      main:
        annotations:
          hajimari.io/icon: mdi:movie
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        enabled: true
        hosts:
          - host: radarr.kubi.${DOMAIN_LOCAL}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
        labels:
          probe: enabled
    persistence:
      config:
        enabled: true
        mountPath: /config
        retain: true
        size: 1Gi
        storageClass: longhorn
      media:
        enabled: true
        mountPath: /media
        path: /tank/Media/Movies
        server: nas
        type: nfs
      tmp:
        enabled: true
        mountPath: /tmp
        type: emptyDir
    service:
      main:
        ports:
          http:
            port: 7878
