---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: traefik
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: traefik
      namespace: kube-system
  providerRef:
    name: alertmanager
