---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-traefik
  namespace: kube-system
spec:
  dnsNames:
    - '*.${DOMAIN_PUBLIC}'
    - '*.kubi.${DOMAIN_LOCAL}'
  secretName: letsencrypt-traefik
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
