---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: hajimari
  namespace: flux-system
spec:
  image: ghcr.io/toboshii/hajimari
  interval: 24h0m0s
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: hajimari
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: hajimari
  filterTags:
    pattern: '^v(?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)$'
    extract: '$major.$minor.$patch'
  policy:
    semver:
      range: '*'
