---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: immich-helm
  namespace: media
spec:
  interval: 5m0s
  url: https://nexus.kubi.${DOMAIN_LOCAL}/repository/immich-helm/
