---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: postgresql-ha
  namespace: flux-system
spec:
  eventSources:
    - kind: HelmRelease
      name: postgresql-ha
      namespace: postgresql-ha
  providerRef:
    name: alertmanager
