apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql-ha
  namespace: postgresql-ha
spec:
  chart:
    spec:
      chart: postgresql-ha
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
      version: 11.9.3 # {"$imagepolicy": "flux-system:postgresql-ha:tag"}
  values:
    env: {} # Necessary for the generic TZ patch to not fail
    fullnameOverride: postgresql-ha
    persistence:
      storageClass: service-replicated-longhorn
      size: 2Gi
      annotations:
        helm.sh/resource-policy: keep
    global:
      postgresql:
        existingSecret: postgresql
    postgresql:
      nodeSelector:
        kubernetes.io/arch: amd64
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
      extraEnvVars:
        - name: TZ
          value: ${TZ}
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 384Mi
    pgpool:
      nodeSelector:
        kubernetes.io/arch: amd64
      extraEnvVars:
        - name: TZ
          value: ${TZ}
      existingSecret: pgpool
      containerSecurityContext:
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          memory: 256Mi
          cpu: 50m
        limits:
          memory: 384Mi
      customUsersSecret: pg-users
      initdbScriptsCM: postgresql-ha-initdb-script
  interval: 1m0s
  timeout: 15m0s
