---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifactory
  namespace: artifactory
spec:
  interval: 1m0s
  timeout: 5m0s
  chart:
    spec:
      chart: artifactory-oss
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: jfrog
        namespace: artifactory
      version: 107.111.8
  values:
    artifactory:
      artifactory:
        persistence:
          storageClassName: longhorn
          size: 1Gi
          # todo: do not prune PVC
      postgresql:
        auth:
          password: foo
          # todo: set this in a secret
        primary:
          persistence:
            size: 1Gi
            storageClass: longhorn
      nginx:
        enabled: false
      ingress:
        enabled: true
        hosts:
          - artifactory.kubi.${DOMAIN_LOCAL}
        annotations:
          hajimari.io/icon: simple-icons:jfrog
          hajimari.io/group: foundation
          hajimari.io/appName: artifactory
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
